/**
 * Task Management System Types
 * 
 * Based on Claude Code's task management philosophy with:
 * - Task dependencies via doubly-linked list (blockedBy / blocks)
 * - High-water mark for unique ID generation
 * - Agent busy checking for task claiming
 * - State machine: pending -> in_progress -> completed/failed/cancelled
 */

/**
 * Task status state machine
 */
export type TaskStatus = 'pending' | 'in_progress' | 'completed' | 'failed' | 'cancelled';

/**
 * Task priority levels
 */
export type TaskPriority = 'low' | 'medium' | 'high';

/**
 * Task metadata for storing additional information
 */
export interface TaskMetadata {
  /** Error message if task failed */
  error?: string;
  /** Result summary if task completed */
  result?: string;
  /** Stop reason if task was stopped */
  stopReason?: string;
  /** Priority level */
  priority?: TaskPriority;
  /** Tags for categorization */
  tags?: string[];
  /** Any additional custom data */
  [key: string]: unknown;
}

/**
 * Core Task interface
 * 
 * Uses doubly-linked list for dependency tracking:
 * - blockedBy: tasks that must complete before this task
 * - blocks: tasks that this task blocks
 */
export interface Task {
  /** Unique task identifier (generated by HighWaterMark) */
  id: string;
  /** Conversation ID this task belongs to */
  conversationId: string;
  /** Task subject/title */
  subject: string;
  /** Current task status */
  status: TaskStatus;
  /** Agent ID currently claiming this task (if in_progress) */
  claimedBy: string | null;
  /** Active form description (what the agent is currently doing) */
  activeForm: string | null;
  /** Task dependencies - IDs of tasks that must complete first */
  blockedBy: string[];
  /** Inverse of blockedBy - IDs of tasks this task blocks */
  blocks: string[];
  /** Creation timestamp */
  createdAt: number;
  /** Last update timestamp */
  updatedAt: number;
  /** Completion timestamp (if completed/failed/cancelled) */
  completedAt: number | null;
  /** Additional metadata */
  metadata: TaskMetadata;
}

/**
 * Input for creating a new task
 */
export interface TaskCreateInput {
  /** Conversation ID this task belongs to (required) */
  conversationId: string;
  /** Task subject/title (required) */
  subject: string;
  /** Initial blockedBy dependencies (optional) */
  blockedBy?: string[];
  /** Initial metadata (optional) */
  metadata?: Partial<TaskMetadata>;
}

/**
 * Input for updating a task
 */
export interface TaskUpdateInput {
  /** Task ID to update */
  id: string;
  /** New status (optional) */
  status?: TaskStatus;
  /** New subject (optional) */
  subject?: string;
  /** Active form description (optional) */
  activeForm?: string | null;
  /** Claimed by agent ID (optional) */
  claimedBy?: string | null;
  /** New blockedBy dependencies (optional) */
  blockedBy?: string[];
  /** New metadata (optional, merged with existing) */
  metadata?: Partial<TaskMetadata>;
}

/**
 * Result of claiming a task
 */
export interface TaskClaimResult {
  /** Whether the claim was successful */
  success: boolean;
  /** The task if successful */
  task?: Task;
  /** Error message if failed */
  message?: string;
}

/**
 * Result of getting available tasks
 */
export interface TaskListResult {
  /** List of available tasks */
  tasks: Task[];
  /** Total count */
  total: number;
}

/**
 * Agent busy status
 */
export interface AgentStatus {
  /** Agent ID */
  agentId: string;
  /** Whether the agent is currently busy */
  isBusy: boolean;
  /** Task ID currently being worked on (if busy) */
  currentTaskId: string | null;
}

/**
 * Task events for event-driven architecture
 */
export type TaskEventType = 
  | 'task:created'
  | 'task:updated'
  | 'task:deleted'
  | 'task:claimed'
  | 'task:completed'
  | 'task:failed'
  | 'task:cancelled'
  | 'task:stopped';

/**
 * Task event payload
 */
export interface TaskEvent {
  type: TaskEventType;
  task: Task;
  timestamp: number;
  metadata?: Record<string, unknown>;
}

/**
 * Task event listener callback
 */
export type TaskEventListener = (event: TaskEvent) => void | Promise<void>;

/**
 * TaskStore interface - defines the contract for task storage implementations
 */
export interface TaskStore {
  /**
   * Create a new task
   */
  createTask(input: TaskCreateInput): Task;
  
  /**
   * Get a task by ID
   */
  getTask(id: string): Task | undefined;
  
  /**
   * Get all tasks
   */
  getAllTasks(): Task[];
  
  /**
   * Get tasks for a specific conversation
   */
  getTasksByConversation(conversationId: string): Task[];
  
  /**
   * Update a task
   */
  updateTask(input: TaskUpdateInput): Task | undefined;
  
  /**
   * Delete a task and clean up dependencies
   */
  deleteTask(id: string): boolean;
  
  /**
   * Claim a task for an agent (with busy checking)
   */
  claimTask(taskId: string, agentId: string): TaskClaimResult;
  
  /**
   * Get tasks available for an agent to claim
   * A task is available if:
   * - status is 'pending'
   * - all blockedBy tasks are 'completed'
   * - not claimed by another agent
   */
  getAvailableTasks(): Task[];
  
  /**
   * Get tasks by status
   */
  getTasksByStatus(status: TaskStatus): Task[];
  
  /**
   * Get tasks claimed by a specific agent
   */
  getTasksByAgent(agentId: string): Task[];
  
  /**
   * Get tasks that a task blocks (direct dependents)
   */
  getBlockingTasks(taskId: string): Task[];
  
  /**
   * Get tasks that a task is blocked by (dependencies)
   */
  getBlockedByTasks(taskId: string): Task[];
  
  /**
   * Subscribe to task events
   */
  subscribe(listener: TaskEventListener): () => void;
  
  /**
   * Get agent's current busy status
   */
  getAgentStatus(agentId: string): AgentStatus;
  
  /**
   * Set agent as busy (claim task) or free (complete task)
   */
  setAgentBusy(agentId: string, busy: boolean, taskId?: string): void;
  
  /**
   * Clear all tasks (for testing)
   */
  clearAllTasks(): void;
}

/**
 * HighWaterMark interface for ID generation
 */
export interface HighWaterMark {
  /**
   * Get the next unique ID
   */
  next(): string;
  
  /**
   * Get the current value without incrementing
   */
  current(): number;
  
  /**
   * Reset to a specific value
   */
  reset(value: number): void;
}

/**
 * Default HighWaterMark instance prefix
 */
export const TASK_ID_PREFIX = 'task-';

/**
 * Status display configuration
 */
export const STATUS_CONFIG = {
  pending: {
    icon: '○',
    color: 'text-gray-400',
    indicator: false,
  },
  in_progress: {
    icon: '◐',
    color: 'text-blue-500',
    indicator: false,
    animation: 'animate-spin',
  },
  completed: {
    icon: '●',
    color: 'text-green-500',
    indicator: true,
  },
  failed: {
    icon: '✕',
    color: 'text-red-500',
    indicator: false,
  },
  cancelled: {
    icon: '⊘',
    color: 'text-gray-400',
    indicator: false,
  },
} as const satisfies Record<TaskStatus, {
  icon: string;
  color: string;
  indicator: boolean;
  animation?: string;
}>;
